events {
  worker_connections 4096; ## Default: 1024
}

http {
  server {
    listen 80;
    server_name localhost;

    location /api/ {
      proxy_pass http://course-backend:8000;
    }

    location / {
      proxy_pass http://course-frontend:3000;
    }
  }
}
